
export enum DexProtocol {
  // V2
  UNISWAP_V2 = 'UNISWAP_V2',
  PANCAKESWAP_V2 = 'PANCAKESWAP_V2',
  BISWAP_V2 = 'BISWAP_V2',
  FUSIONX_V2 = 'FUSIONX_V2',
  SUSHISWAP_V2 = 'SUSHISWAP_V2',
  QUICKSWAP_V2 = 'QUICKSWAP_V2',
  DFYN = 'DFYN',
  BUTTER = 'BUTTER',
  MERCHANT_MOE = 'MERCHANT_MOE',
  POLYCAT = 'POLYCAT',
  APESWAP = 'APESWAP',
  WAULTSWAP = 'WAULTSWAP',
  COMETH = 'COMETH',
  TROPICAL_SWAP = 'TROPICAL_SWAP',
  MANTLESWAP = 'MANTLESWAP',
  DTX_V1 = 'DTX_V1',
  TAIKOSWAP = 'TAIKOSWAP',
  PASS = 'PASS',
  // exotic
  DODO_V1 = 'DODO_V1',
  DODO_V2 = 'DODO_V2',
  // Solidlies
  VELOCIMETER_VOLATILE = 'VELOCIMETER_VOLATILE',
  VELOCIMETER_STABLE = 'VELOCIMETER_STABLE',
  CLEOPATRA_V1_VOLATILE = 'CLEOPATRA_V1_VOLATILE',
  CLEOPATRA_V1_STABLE = 'CLEOPATRA_V1_STABLE',
  STRATUM_VOLATILE = 'STRATUM_VOLATILE',
  STRATUM_STABLE = 'STRATUM_STABLE',
  DYSTOPIA_VOLATILE = 'DYSTOPIA_VOLATILE',
  DYSTOPIA_STABLE = 'DYSTOPIA_STABLE',
  KODO_VOLATILE = 'KODO_VOLATILE',
  KODO_STABLE = 'KODO_STABLE',
  CRUST_V1_VOLATILE = 'CRUST_V1_VOLATILE',
  CRUST_V1_STABLE = 'CRUST_V1_STABLE',
  RAMSES_V1_VOLATILE = 'RAMSES_V1_VOLATILE',
  RAMSES_V1_STABLE = 'RAMSES_V1_STABLE',
  CAMELOT_V2_VOLATILE = 'CAMELOT_V2_VOLATILE',
  CAMELOT_V2_STABLE = 'CAMELOT_V2_STABLE',
  // stable
  PANCAKE_STABLE = 'PANCAKE_STABLE',
  FUSIONX_STABLE = 'FUSIONX_STABLE',
  // V3
  UNISWAP_V3 = 'UNISWAP_V3',
  DACKIESWAP_V3 = 'DACKIESWAP_V3',
  ALIENBASE_V3 = 'ALIENBASE_V3',
  BASEX_V3 = 'BASEX_V3',
  KINETIX_V3 = 'KINETIX_V3',
  PANCAKESWAP_V3 = 'PANCAKESWAP_V3',
  BISWAP_V3 = 'BISWAP_V3',
  FUSIONX_V3 = 'FUSIONX_V3',
  QUICKSWAP_V3 = 'QUICKSWAP_V3',
  SUSHISWAP_V3 = 'SUSHISWAP_V3',
  SOLIDLY_V3 = 'SOLIDLY_V3',
  IZUMI = 'IZUMI',
  AGNI = 'AGNI',
  SWAPSICLE = 'SWAPSICLE',
  RETRO = 'RETRO',
  CLEOPATRA = 'CLEOPATRA',
  METHLAB = 'METHLAB',
  HENJIN = 'HENJIN',
  CAMELOT = 'CAMELOT',
  DTX = 'DTX',
  CRUST = 'CRUST',
  PANKO = 'PANKO',
  RAMSES_V2 = 'RAMSES_V2',
  // multi asset
  WOO_FI = 'WOO_FI',

  // Curve main pool types by fetching
  CURVE_V1_CLASSIC = 'CURVE_V1_CLASSIC',
  CURVE_NG = 'CURVE_NG',
  CURVE_CRYPTO = 'CURVE_CRYPTO',
  // Curve main pool types by swap execution
  // these are not dependent on the fetch category
  CURVE_STANDARD = 'CURVE_STANDARD',
  CURVE_RECEIVE = 'CURVE_RECEIVE',

  // curve forks 
  STRATUM_CURVE_STABLE = 'STRATUM_CURVE_STABLE',
  STRATUM_CURVE = 'STRATUM_CURVE',
  PANKO_STABLE = 'PANKO_STABLE',
  // GMX
  KTX = 'KTX',
  // tradejoe
  MERCHANT_MOE_LB = 'MERCHANT_MOE_LB',
  // syncswap
  RITSU_BASE = 'RITSU_BASE',
  RITSU_RYTHM = 'RITSU_RYTHM',
  RITSU_STABLE = 'RITSU_STABLE',

  // fuel
  MIRA_VOLATILE = 'MIRA_VOLATILE',
  MIRA_STABLE = 'MIRA_STABLE',
  DIESEL_VOLATILE = 'DIESEL_VOLATILE',
  DIESEL_STABLE = 'DIESEL_STABLE',
}