// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library TokensArbitrum {
    address internal constant USDCE = 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8;
    address internal constant WETH = 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1;
    address internal constant USDC = 0xaf88d065e77c8cC2239327C5EDb3A432268e5831;
    address internal constant USDT = 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9;
    address internal constant WSTETH = 0x5979D7b546E38E414F7E9822514be443A4800529;
    address internal constant ARB = 0x912CE59144191C1204E64559FE8253a0e49E6548;
    address internal constant WBTC = 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f;
    address internal constant DAI = 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1;

    address internal constant SolvBTC = 0x3647c54c4c2C65bC7a2D63c0Da2809B399DBBDC0;
    address internal constant SolvBTC_ENA = 0xaFAfd68AFe3fe65d376eEC9Eab1802616cFacCb8;
    address internal constant SolvBTC_BBN = 0x346c574C56e1A4aAa8dc88Cda8F7EB12b39947aB;

    address internal constant PUMP_BTC = 0x9a02588DDff4d079cC5BEB1b864B12410049288a;
}
