// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library TokensPolygon {
    address internal constant wbpg = 0xc0f14C88250E680eCd70224B7fBa82b7C6560d12;

    address internal constant crvUSD = 0xc4Ce1D6F5D98D65eE25Cf85e9F2E9DcFEe6Cb5d6;

    address internal constant WMATIC = 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270;

    address internal constant DAI = 0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063;

    address internal constant LINK = 0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39;

    address internal constant USDC = 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174;

    address internal constant WBTC = 0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6;

    address internal constant WETH = 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619;

    address internal constant USDT = 0xc2132D05D31c914a87C6611C10748AEb04B58e8F;

    address internal constant AAVE = 0xD6DF932A45C0f255f85145f286eA0b292B21C90B;

    address internal constant CRV = 0x172370d5Cd63279eFa6d502DAB29171933a610AF;

    address internal constant SUSHI = 0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a;

    address internal constant GHST = 0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7;

    address internal constant BAL = 0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3;

    address internal constant DPI = 0x85955046DF4668e1DD369D2DE9f3AEB98DD2A369;

    address internal constant EURS = 0xE111178A87A3BFf0c8d18DECBa5798827539Ae99;

    address internal constant jEUR = 0x4e3Decbb3645551B8A19f0eA1678079FCB33fB4c;

    address internal constant EURA = 0xE0B52e49357Fd4DAf2c15e02058DCE6BC0057db4;

    address internal constant miMATIC = 0xa3Fa99A148fA48D14Ed51d610c367C61876997F1;

    address internal constant stMATIC = 0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4;

    address internal constant MaticX = 0xfa68FB4628DFF1028CFEc22b4162FCcd0d45efb6;

    address internal constant wstETH = 0x03b54A6e9a984069379fae1a4fC4dBAE93B3bCCD;

    address internal constant USDCn = 0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359;
}
