// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library CompoundV3Polygon {
    address internal constant COMET_USDC = 0xF25212E676D1F7F89Cd72fFEe66158f541246445;
    address internal constant COMET_USDT = 0xaeB318360f27748Acb200CE616E389A6C9409a07;
}
