// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library YldrPolygon {
    address internal constant POOL = 0x8183D4e0561cBdc6acC0Bdb963c352606A2Fa76F;
}

library YldrPolygonAssets {
    address internal constant USDC_A_TOKEN = 0xAFcc7719EdfCba9215749c8e399f4E20c9024Cf7;
    address internal constant USDC_V_TOKEN = 0x42037D996611eD4378A508F67470fBcED1436555;

    address internal constant USDCn_A_TOKEN = 0xd8aB1E396Cfc5d9D7922e2Ca0B9084aB64DD6Cee;
    address internal constant USDCn_V_TOKEN = 0x477768d8230F2B914554491414d5e76C73314eD2;

    address internal constant WETH_A_TOKEN = 0xD85552A6e8DF8dCe06B157d33B383CE9F5f9aDe2;
    address internal constant WETH_V_TOKEN = 0x2Cd174A79F40E67D390C12Ced441b17De70f9765;
    address internal constant USDT_A_TOKEN = 0xf309Ada8651891a99B251cAb253aD10895b3D028;
    address internal constant USDT_V_TOKEN = 0x9113F0D78bC64712e9560f58DC0749e6ac227fff;

    address internal constant WMATIC_A_TOKEN = 0xf6535aa0cD4988855247cbEFa7fbe64E3E78e024;
    address internal constant WMATIC_V_TOKEN = 0x23219a2d278E99B0F170ad963d34373069159Ab1;

    address internal constant WBTC_A_TOKEN = 0x62B1bf965cc3051c73e0DB6b2025cBC371b6ea9c;
    address internal constant WBTC_V_TOKEN = 0x87B98Ef3AE0488fe509a129025988956a8962EDA;
}
