// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library AureliusMantle {
    address internal constant POOL = 0x7c9C6F5BEd9Cfe5B9070C7D3322CF39eAD2F9492;
}

library AureliusMantleAssets {
    address internal constant USDT_A_TOKEN = 0x893DA3225a2FCF13cCA674d1A1bb5a2eA1F3DD14;
    address internal constant USDC_A_TOKEN = 0x833b5C0379A597351c6Cd3eFE246534bf3aE5f9F;
    address internal constant WETH_A_TOKEN = 0xc3B515BCa486520483EF182c3128F72ce270C069;
    address internal constant WMNT_A_TOKEN = 0x067DDc903148968d49AbC3144fd7619820F16949;
    address internal constant WBTC_A_TOKEN = 0xF91798762cc61971df6Df0e15F0904e174387477;
    address internal constant METH_A_TOKEN = 0xBb406187C01cC1c9EAf9d4b5C924b7FA37aeCEFD;

    address internal constant USDT_V_TOKEN = 0xc799FE29b67599010A55Ec14a8031aF2a2521470;
    address internal constant USDC_V_TOKEN = 0xaA9c890CA3E6B163487dE3C11847B50e48230b45;
    address internal constant WETH_V_TOKEN = 0x45cccE9bC8e883ef7805Ea73B88D5D528C7CEc55;
    address internal constant WMNT_V_TOKEN = 0x4C3c0650DdCB767D71c91fA89ee9e5a2CD335834;
    address internal constant WBTC_V_TOKEN = 0xd632fd1D737c6Db356D747D09642Bef8Ae453f4D;
    address internal constant METH_V_TOKEN = 0x00dFD5F920CCf08eB0581D605BAb413d289c21b4;

    address internal constant USDT_S_TOKEN = 0x61627C3E37A4e57A4Edb5cd52Ce8221d9C5bDA3d;
    address internal constant USDC_S_TOKEN = 0xB41Cf1EEAdfD17FBc0086E9e856f1ac5460064d2;
    address internal constant WETH_S_TOKEN = 0xFbacE7bf40Dd1B9158236a23e96C11eBD03a2D42;
    address internal constant WMNT_S_TOKEN = 0x6110868e963F8Badf4D79Bc79C8Ac1e13cd59735;
    address internal constant WBTC_S_TOKEN = 0xBc9B223D335c624f55C8b3a70f883FfEFB890A0E;
    address internal constant METH_S_TOKEN = 0x2D422c5EaD5fA3c26aeC97D070343353e2086A1d;
}
