// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library LendleMantle {
    address internal constant POOL = 0xCFa5aE7c2CE8Fadc6426C1ff872cA45378Fb7cF3;
}

library LendleMantleAssets {
    address internal constant USDT_A_TOKEN = 0xE71cbaaa6B093FcE66211E6f218780685077D8B5;
    address internal constant USDC_A_TOKEN = 0xF36AFb467D1f05541d998BBBcd5F7167D67bd8fC;
    address internal constant WETH_A_TOKEN = 0x787Cb0D29194f0fAcA73884C383CF4d2501bb874;
    address internal constant WMNT_A_TOKEN = 0x683696523512636B46A826A7e3D1B0658E8e2e1c;
    address internal constant WBTC_A_TOKEN = 0x44CCCBbD7A5A9e2202076ea80C185DA0058f1715;
    address internal constant METH_A_TOKEN = 0x0e927Aa52A38783C1Fd5DfA5c8873cbdBd01D2Ca;

    address internal constant USDT_V_TOKEN = 0xaC3c14071c80819113DF501E1AB767be910d5e5a;
    address internal constant USDC_V_TOKEN = 0x334a542b51212b8Bcd6F96EfD718D55A9b7D1c35;
    address internal constant WETH_V_TOKEN = 0x5DF9a4BE4F9D717b2bFEce9eC350DcF4cbCb91d8;
    address internal constant WMNT_V_TOKEN = 0x18d3E4F9951fedcdDD806538857eBED2F5F423B7;
    address internal constant WBTC_V_TOKEN = 0x42f9F9202D5F4412148662Cf3bC68D704c8E354f;
    address internal constant METH_V_TOKEN = 0xd739fB7a3b652306d00F92b20439aFC637650254;

    address internal constant USDT_S_TOKEN = 0xEA8BD20f6c5424Ab4acf132c70b6C7355e11F62e;
    address internal constant USDC_S_TOKEN = 0xEe8D412A4EF6613c08889f9CD1Fd7D4a065f9A8B;
    address internal constant WETH_S_TOKEN = 0x0cA5e3CD5f3273B066422291edDa3768451FbB68;
    address internal constant WMNT_S_TOKEN = 0xafefc53Be7e32C7510f054Abb1ec5E44C03fCCaB;
    address internal constant WBTC_S_TOKEN = 0x1817Cde5CD6423C3b87039e1CB000BB2aC4E05c7;
    address internal constant METH_S_TOKEN = 0x614110493CEAe1171532eB635242E4ca71CcBBa2;
}
