// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library AvalonArbitrum {
    address internal constant POOL = 0xe1ee45DB12ac98d16F1342a03c93673d74527b55;
}

library AvalonArbitrumAssets {
    address internal constant DAI_A_TOKEN = 0x09586F5EEF369909F321F9A313B6D51db1946119;
    address internal constant USDC_A_TOKEN = 0xb05088c49F74092A1fDa87257648f92ad0547753;
    address internal constant WBTC_A_TOKEN = 0x5D383D2A1Dc3e5E82ACb2035C10ba1bAC989fE42;
    address internal constant WETH_A_TOKEN = 0xb57905AB2c72E4354acbA8A885294de277c0A7AE;
    address internal constant USDT_A_TOKEN = 0xABc4B43c27b458745a802E8Fa3D00c5E96Db0BfC;
    address internal constant SOLVBTC_A_TOKEN = 0x3e5E8569B2aa2A8Bd235104944868913B23a0D64;
    address internal constant SOLVBTCENA_A_TOKEN = 0x039FAd6071212aC685833F2060D29cd9F75d8ad7;
    address internal constant SOLVBTCBBN_A_TOKEN = 0x95118fb8aeD1877DB25E5F72d319b7aE45E9D101;

    address internal constant DAI_V_TOKEN = 0x2B8360cfC4d18D0C614C8e3BaD1990858b9b68C0;
    address internal constant USDC_V_TOKEN = 0x15D67fA0a1e579765d0E9211313E4d0F5788256f;
    address internal constant WBTC_V_TOKEN = 0x703cC5Fca1c0BCb3446E20bf52Ab9C5A188c9425;
    address internal constant WETH_V_TOKEN = 0xa8c3064709A53F8d1C5784b060b29464028C61c4;
    address internal constant USDT_V_TOKEN = 0x9dCa1b6E1F62b324166De1c2Ae7B640fAD80a237;
    address internal constant SOLVBTC_V_TOKEN = 0x504ED6c8A0c5b04990dA91C0bf9d11f6Ee2e6C28;
    address internal constant SOLVBTCENA_V_TOKEN = 0xF14f9F26AC113c1899d4c1eaaF67d4c04A2b5565;
    address internal constant SOLVBTCBBN_V_TOKEN = 0x93c138D0295a1b1a715B2751d286732D8F2f4A92;
}

library AvalonPumpBTCArbitrum {
    address internal constant POOL = 0x4B801fb6f0830D070f40aff9ADFC8f6939Cc1F8D;
}

library AvalonPumpBTCArbitrumAssets {
    address internal constant PUMP_BTC_A_TOKEN = 0x9a02588DDff4d079cC5BEB1b864B12410049288a;
    address internal constant WBTC_A_TOKEN = 0x0b37eE41a3b80431A444d7F3d9F0edE9023BE000;

    address internal constant PUMP_BTC_V_TOKEN = address(0);
    address internal constant WBTC_V_TOKEN = 0xCb4d00EaaF3562469a397994897e7384A124395a;
}
