// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library VenusCoreArbitrum {
    address internal constant COMPTROLLER = 0x317c1A5739F39046E20b08ac9BeEa3f10fD43326;

    // tokens

    address internal constant ARB_A_TOKEN = 0xAeB0FEd69354f34831fe1D16475D9A83ddaCaDA6;

    address internal constant USDC_A_TOKEN = 0x7D8609f8da70fF9027E9bc5229Af4F6727662707;

    address internal constant USDT_A_TOKEN = 0xB9F9117d4200dC296F9AcD1e8bE1937df834a2fD;

    address internal constant WBTC_A_TOKEN = 0xaDa57840B372D4c28623E87FC175dE8490792811;

    address internal constant WETH_A_TOKEN = 0x68a34332983f4Bf866768DD6D6E638b02eF5e1f0;
}

library VenusEtherArbitrum {
    address internal constant COMPTROLLER = 0x52bAB1aF7Ff770551BD05b9FC2329a0Bf5E23F16;

    // tokens

    address internal constant WEETH = 0x246a35E79a3a0618535A469aDaF5091cAA9f7E88;

    address internal constant WETH = 0x39D6d13Ea59548637104E40e729E4aABE27FE106;

    address internal constant WSTETH = 0x9df6B5132135f14719696bBAe3C54BAb272fDb16;
}
