// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library YldrArbitrum {
    address internal constant POOL = 0x54aD657851b6Ae95bA3380704996CAAd4b7751A3;
}

library YldrArbitrumAssets {
    address internal constant USDC_A_TOKEN = 0xAA40dcA2d69DED3Eb17991AA17D83653F1084091;
    address internal constant WETH_A_TOKEN = 0x6d7197fa1f2b9D01a25705b5558a748A2b5f0605;
    address internal constant USDCE_A_TOKEN = 0x8F46fB23d1D7e1385809bC304f979651fD374DEb;
    address internal constant USDT_A_TOKEN = 0x172c9dCe43198154dc0DAcc843fd8103aD09145C;
    address internal constant WSTETH_A_TOKEN = 0x4107B60471eEf310fCe240e4dfad14b7e326a6E0;
    address internal constant ARB_A_TOKEN = 0x609772EEeDa6Dd1537177737823fFB3b3Bc9b6e4;
    address internal constant WBTC_A_TOKEN = 0xCB14E172f16Db1e8E3CBCA41a56281022633414d;
    address internal constant DAI_A_TOKEN = 0x43274582edbc3d17ccB8c752da8aA9D471B5A093;

    address internal constant USDC_V_TOKEN = 0x7Bcc957F8f86Aa78762FCCC0bFeC6DbF8b1Ad987;
    address internal constant WETH_V_TOKEN = 0xa350429bC896A95f1EF6936e4C4C5a2C62052ED1;
    address internal constant USDCE_V_TOKEN = 0x57c2e352E867238A96C300ff6434f7C8D63b3C14;
    address internal constant USDT_V_TOKEN = 0xCdA3934B7dDA7Fc07ff09e669137c49782812f82;
    address internal constant WSTETH_V_TOKEN = 0x16359d6CF2ec7f9020707653D4758Ad8969752F0;
    address internal constant ARB_V_TOKEN = 0xDA27Be910cA3E205927Cc43088B5681D19DE05FA;
    address internal constant WBTC_V_TOKEN = 0xD5C41944A760C23Caa11815c47e43b66719A213D;
    address internal constant DAI_V_TOKEN = 0x23a12B967AC30E04e844af3017F5c80B115b476d;
}
