// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library AvalonTaiko {
    address internal constant POOL = 0x9dd29AA2BD662E6b569524ba00C55be39e7B00fB;
}

library AvalonTaikoAssets {
    address internal constant SOLV_BTC_A_TOKEN = 0x8C9510db49b00F44e9C358016E95C8103b362bDe;
    address internal constant SOLV_BTC_BBN_A_TOKEN = 0x2e7dc6260112F2d496A9Ff7D0A5CC38B3eaddDba;

    address internal constant SOLV_BTC_V_TOKEN = 0xF8B03861429336D592225a404360EE96C7Cbc411;
    address internal constant SOLV_BTC_BBN_V_TOKEN = 0xaE28c4d9EC1F095aE9151c13B29c58c74e020141;

    address internal constant SOLV_BTC_S_TOKEN = address(0);
    address internal constant SOLV_BTC_BBN_S_TOKEN = address(0);
}
