// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library HanaTaiko {
    address internal constant POOL = 0x4aB85Bf9EA548410023b25a13031E91B4c4f3b91;
}

library HanaTaikoAssets {
    address internal constant TAIKO_A_TOKEN = 0x67F1E0A9c9D540F61D50B974DBd63aABf636a296;
    address internal constant USDC_A_TOKEN = 0x5C9bC967E338F48535c3DF7f80F2DB0A366D36b2;
    address internal constant WETH_A_TOKEN = 0xacd2E13C933aE1EF97698f00D14117BB70C77Ef1;

    address internal constant TAIKO_V_TOKEN = 0x1592Ff6f057d65a17Be56116e2B3cbfD4d2314C2;
    address internal constant USDC_V_TOKEN = 0x0247606c3D3F62213bbC9D7373318369e6860eb1;
    address internal constant WETH_V_TOKEN = 0xf1777EAD4098F574c68E59905588f3C9875251ed;

    address internal constant TAIKO_S_TOKEN = address(0);
    address internal constant USDC_S_TOKEN = address(0);
    address internal constant WETH_S_TOKEN = address(0);
}
