// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library TakoTakoTaiko {
    address internal constant POOL = 0x3A2Fd8a16030fFa8D66E47C3f1C0507c673C841e;
}

library TakoTakoTaikoAssets {
    address internal constant TAIKO_A_TOKEN = 0xbbFa45a92d9d071554B59D2d29174584D9b06bc3;
    address internal constant USDC_A_TOKEN = 0x79a741EBFE9c323CF63180c405c050cdD98c21d8;
    address internal constant WETH_A_TOKEN = 0x6Afa285ab05657f7102F66F1B384347aEF3Ef6Aa;

    address internal constant TAIKO_V_TOKEN = 0x0f0244337f1215E6D8e13Af1b5ae639244d8a6f6;
    address internal constant USDC_V_TOKEN = 0x72C6bDf69952b6bc8aCc18c178d9E03EAc5eaD50;
    address internal constant WETH_V_TOKEN = 0x19871b9911ddbd422e06F66427768f9B65d36F81;

    address internal constant TAIKO_S_TOKEN = address(0);
    address internal constant USDC_S_TOKEN = address(0);
    address internal constant WETH_S_TOKEN = address(0);
}
