// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library TokensTaiko {
    address internal constant WETH = 0xA51894664A773981C6C112C43ce576f315d5b1B6;
    address internal constant SOLV_BTC_BBN = 0xCC0966D8418d412c599A6421b760a847eB169A8c;
    address internal constant SOLV_BTC = 0x541FD749419CA806a8bc7da8ac23D346f2dF8B77;
    address internal constant USDC = 0x07d83526730c7438048D55A4fc0b850e2aaB6f0b;
    address internal constant sgUSDC = 0x19e26B0638bf63aa9fa4d14c6baF8D52eBE86C5C;
    address internal constant TAIKO = 0xA9d23408b9bA935c230493c40C73824Df71A0975;
    address internal constant USDT = 0x2DEF195713CF4a606B49D07E520e22C17899a736;
    address internal constant stBTC = 0xf6718b2701D4a6498eF77D7c152b2137Ab28b8A3;
    address internal constant enzoBTC = 0x6A9A65B84843F5fD4aC9a0471C4fc11AFfFBce4a;
}
