// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library TokensMantle {
    address internal constant WETH = 0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111;
    address internal constant WBTC = 0xCAbAE6f6Ea1ecaB08Ad02fE02ce9A44F09aebfA2;
    address internal constant WMNT = 0x78c1b0C915c4FAA5FffA6CAbf0219DA63d7f4cb8;
    address internal constant CLEO = 0xC1E0C8C30F251A07a894609616580ad2CEb547F2;
    address internal constant USDC = 0x09Bc4E0D864854c6aFB6eB9A9cdF58aC190D0dF9;
    address internal constant USDT = 0x201EBa5CC46D216Ce6DC03F6a759e8E766e956aE;
    address internal constant METH = 0xcDA86A272531e8640cD7F1a92c01839911B90bb0;

    address internal constant axlFRAX = 0x406Cde76a3fD20e48bc1E0F60651e60Ae204B040;
    address internal constant axlUSDC = 0xEB466342C4d449BC9f53A865D5Cb90586f405215;
    address internal constant USDY = 0x5bE26527e817998A7206475496fDE1E68957c5A6;
    address internal constant mUSD = 0xab575258d37EaA5C8956EfABe71F4eE8F6397cF3;
    address internal constant USDe = 0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34;
    address internal constant PUFF = 0x26a6b0dcdCfb981362aFA56D581e4A7dBA3Be140;
    address internal constant aUSD = 0xD2B4C9B0d70e3Da1fBDD98f469bD02E77E12FC79;
    address internal constant FBTC = 0xC96dE26018A54D51c097160568752c4E3BD6C364;
    address internal constant LEND = 0x25356aeca4210eF7553140edb9b8026089E49396;
}
